---
- name: install nginx
  yum: name=nginx state=present

- name: copy nginx configuration
  template: src=default.conf dest=/etc/nginx/conf.d/default.conf
  notify: restart nginx

- name: start firewalld 
  service: name=firewalld state=started

- name: insert firewalld rule for nginx
  firewalld: port={{nginx_port}}/tcp permanent=true state=enabled immediate=yes
