---
- name: get logstash RPM
  get_url:
    url: "{{logstashURL}}"
    checksum: "{{logstashChecksum}}"
    dest: /tmp/

- name: install logstash
  yum:
    name: /tmp/logstash-5.2.1.rpm 
    state: present

- name: point config file to our elk server
  lineinfile:
    destfile: /etc/pki/tls/openssl.cnf
    regexp: 'subjectAltName ='
    line: 'subjectAltName = IP: {{elk_ip}}'

- name: generate ssl certificate
  shell: "openssl req -config /etc/pki/tls/openssl.cnf -x509 -days 3650 -batch -nodes -newkey rsa:2048 -keyout /etc/pki/tls/private/logstash-forwarder.key -out /etc/pki/tls/certs/logstash-forwarder.crt"

- name: create logstash configuration files
  template: 
    src: "{{item}}.j2"
    dest: "/etc/logstash/conf.d/{{item}}"
    owner: root
    group: root
    mode: 0644
  with_items:
  - 02-beats-input.conf
  - 10-syslog-filter.conf
  - 30-elasticsearch-output.conf
  notify: restart logstash

- name: start logstash
  service:
    name: logstash
    enabled: yes
    state: started
